
ALTER TABLE Gym
ADD FOREIGN KEY(FacilityId) REFERENCES Facility(FacilityId)
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE ChessRoom
ADD FOREIGN KEY(FacilityId) REFERENCES Facility(FacilityId)
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE Facility
ADD FOREIGN KEY(ServiceId) REFERENCES Service(ServiceId)
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE Food
ADD FOREIGN KEY(ServiceId) REFERENCES Service(ServiceId)
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE Contact
ADD FOREIGN KEY(GId) REFERENCES Guest(GId)
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE Bill
ADD FOREIGN KEY(EId) REFERENCES Reserve(EmpId) 
ON DELETE SET NULL ON UPDATE CASCADE,
ADD FOREIGN KEY(GId) REFERENCES Reserve(GId) 
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE Bill
ADD FOREIGN KEY(ResId) REFERENCES Reserve(ResId) 
ON DELETE SET NULL ON UPDATE CASCADE;